### ISSUE TITLE
Campo detalles no existe en 

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_libro_compra_venta#3]
En  [este commit](https://github.com/dansanti/l10n_cl_libro_compra_venta/commit/b763de647eb03dd5e3e166cf066f301282b70a12)  [linea 291](https://github.com/dansanti/l10n_cl_libro_compra_venta/blob/9.0/models/libro.py#L291) se hace referencia al campo detalles del modelo account.move.consumo_folios, pero este no existe, por lo que sale error, por favor verificar

**Comment by dansanti** [comment]
Los commits a consumo de folios no estan listos aún en la noche termino de
hacerlos, dentro de ellos está ese nuevo campo

**Comment by dansanti** [comment]
https://github.com/dansanti/l10n_cl_libro_compra_venta/commit/0a4a241eafc9aa27ac640fb6d7d993ca7b553f2b
