### ISSUE TITLE
Elemento TasaIVA no debe ir en xml de consumo de folios

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_libro_compra_venta#4]
Cuando se genera el consumo de folios y se pasa el elemento TasaIVA al xml de consumo de folios, sale el siguiente error al validar el consumo y generar el xml, entiendo q en el esquema de validacion del xml ese elemento no es esperado, es decir no deberia pasarse eso, si comento [estas lineas de codigo], funciona bien, xq pasan ese elemento TasaIVA entonces, donde dice q es necesario en el cnsumo de folios??? (https://github.com/dansanti/l10n_cl_libro_compra_venta/blob/88ef5078c4ec6b01be1f58ba3b1c31eee70866f4/models/consumo_folios.py#L796)

![image](https://user-images.githubusercontent.com/7775116/30342948-4159f262-97c1-11e7-8db4-b7c7098fd357.png)

**Comment by dansanti** [comment]
que versión tienes?, eso es un error extraño, debes revisar si están puestos bien las configuraciones de impuestos, deben estar marcado con iva incluido y con el código sii 14, 

La línea que muestras, solamente pasa por parámetro, no se asigna directo al xml

también puede ser porque un producto no tenga asigando impuesto,

**Comment by celm1990** [comment]
En este commit ab3ce912b5d2a92c242f9bd730888e64eaaa8653 se cambio algo, asi que cierro este bug ysi el error persiste creo uno nuevo
